FX2LIBDIR=/media/ssaury1/BUF/Work/Aessent/progs/aes220/RevP2/device
#FX2LIBDIR=/media/ssaury1/BUF/Programming/fx2/fx2lib-100127/
BASENAME = reset
SOURCES=reset.c fx2_c0.c
A51_SOURCES=dscr.a51

include $(FX2LIBDIR)/lib/fx2.mk

VID=0x2443
PID=0x00dc
